# TFL Generator configuration file
# Non-sensitive config goes here, sensitive info (like passwords) goes in .env file

# Tableau Prep version info, no changes needed
prep:
  version: "2019.1.3"
  year: 2019
  quarter: 1
  release: 3

# Tableau Server configuration
tableau_server:
  url: "http://win-picvs30bivi"
  default_project: "数据源"
  project_luid: "7fa01ebc-72f4-4fd0-a27f-f8ac1e30ac20"

# Default database configuration
database:
  host: "localhost"
  port: 3306
  dbname: "superstore"
  type: "mysql"       # mysql, postgres, oracle, sqlserver

  # host: "rm-uf661w842h18w326nvo.mysql.rds.aliyuncs.com"
  # port: 3306
  # dbname: "voxadmin"
  # type: "mysql"       # mysql, postgres, oracle, sqlserver
