# TFL Generator 配置文件
# 非敏感配置放在这里，敏感信息（如密码）放在 .env 文件中

# Tableau Prep 版本信息，不需要改
prep:
  version: "2019.1.3"
  year: 2019
  quarter: 1
  release: 3

# Tableau Server 配置
tableau_server:
  url: "http://win-picvs30bivi"
  default_project: "数据源"
  project_luid: "7fa01ebc-72f4-4fd0-a27f-f8ac1e30ac20"

# 默认数据库配置
database:
  host: "rm-uf661w842h18w326nvo.mysql.rds.aliyuncs.com"
  port: 3306
  dbname: "voxadmin"
  type: "mysql"       # mysql, postgres, oracle, sqlserver
